import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

export const projectsSidebar: SidebarsConfig[string] = [{
  type: "autogenerated",
  dirName: "projects",
}];

export const writingSidebar: SidebarsConfig[string] = [{
  type: "autogenerated",
  dirName: "writing",
}];

const sidebars: SidebarsConfig = {
  projectsSidebar,
  writingSidebar,
};

export default sidebars;
