import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    {
      type: "autogenerated",
      dirName: "projects",
    },
  ],
  writingSidebar: [
    {
      type: "autogenerated",
      dirName: "writing",
    },
  ],
};

export default sidebars;
